# This is a config for E2B sandbox template.
# You can use template ID (vho1c304jo2hr3dzl0ij) or template name (unlovable-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("unlovable-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("unlovable-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('unlovable-nextjs')

team_id = "42643265-d306-468d-aac8-71f09b7fb55c"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "unlovable-nextjs"
template_id = "vho1c304jo2hr3dzl0ij"
